version: '3.7'

services:

    jenkins:
        build:
            context: ./jenkins_config
            dockerfile: Dockerfile
        image: jenkins-pact-ci
        container_name: jenkins-pact-ci
        restart: always
        expose:
            - 8080
            - 50000
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            PLUGINS_FORCE_UPGRADE: "true"
        network_mode: "host"    

    postgres:
        image: postgres:12.4-alpine
        restart: unless-stopped
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        network_mode: "host"   

    pact_broker:
        image: pactfoundation/pact-broker:2.73.0.0
        container_name: pact_broker
        expose:
            - 9292
        depends_on:
            - postgres
        environment:
            PACT_BROKER_DATABASE_USERNAME: postgres
            PACT_BROKER_DATABASE_PASSWORD: password
            PACT_BROKER_DATABASE_HOST: localhost
            PACT_BROKER_DATABASE_NAME: postgres
            PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http https
            PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: 5
        network_mode: "host"  