version: '3.3'

services:
    jenkins:
        build:
            context: ./jenkins_config
            dockerfile: Dockerfile
        image: jenkins-pact-ci
        container_name: jenkins-pact-ci
        restart: always
        ports:
            - '8080:8080'
            - '50000:50000'
        environment:
            PLUGINS_FORCE_UPGRADE: "true"
        networks: 
            - "pact"
            
    postgres:
        image: postgres:12.4-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        networks: 
            - "pact"
    
    pact_broker:
        image: pactfoundation/pact-broker:2.73.0.0
        restart: always
        container_name: pact_broker
        ports:
            - "80:80"
        links:
            - jenkins
            - postgres
        environment:
            PACT_BROKER_DATABASE_USERNAME: postgres
            PACT_BROKER_DATABASE_PASSWORD: password
            PACT_BROKER_DATABASE_HOST: postgres
            PACT_BROKER_DATABASE_NAME: postgres
            PACT_BROKER_PORT: 80
            PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http 
            PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: 5
        networks: 
            - "pact"

networks: 
    pact: